spring:
  application:
    name: reservation-system
  profiles:
    active: local
    group:
      local: common, secret
      blue: common, secret
      green: common, secret

---
spring:
  config:
    activate:
      on-profile: local

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

server:
  port: 8080
  serverAddress: localhost
  env: local

serverName: local_server

---
spring:
  config:
    activate:
      on-profile: blue

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://15.165.103.103:8080/login/oauth2/code/google
          naver:
            redirect-uri: http://15.165.103.103:8080/login/oauth2/code/naver
          kakao:
            redirect-uri: http://15.165.103.103:8080/login/oauth2/code/kakao

server:
  port: 8080
  serverAddress: 15.165.103.103
  env: blue

serverName: blue_server

---
spring:
  config:
    activate:
      on-profile: green

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://15.165.103.103:8081/login/oauth2/code/google
          naver:
            redirect-uri: http://15.165.103.103:8081/login/oauth2/code/naver
          kakao:
            redirect-uri: http://15.165.103.103:8081/login/oauth2/code/kakao

server:
  port: 8081
  serverAddress: 15.165.103.103
  env: green

serverName: green_server
